import os
from datetime import datetime
from config import ENV_VAR_NAME


def log_conv(prompt: str, response: str):
    """
    :param prompt: prompt asked by the user
    :param response: response generated by the language model

    Logs the conversation between user and the model. Save path is specified in `config.py`
    """
    date_str = datetime.today().strftime('%Y-%m-%d %H-%M-%S')
    # check if environment variable is set
    if ENV_VAR_NAME in os.environ:
        file_path = os.environ[ENV_VAR_NAME]
        with open(file_path, 'a+') as fp:
            fp.write(f'$ {prompt}\n{response}\n')
    else:
        # if not set a new one and call logging function anew
        os.environ[ENV_VAR_NAME] = os.path.join('..', 'logs', fr'log_{date_str}.txt')
        log_conv(prompt, response)


def clean():
    """
    unsets the environment variable used for logging
    """
    if ENV_VAR_NAME in os.environ:
        del os.environ[ENV_VAR_NAME]
